### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by dany-cmd** [ruan-xian/POCRA#1]
Hey ruan-xian,
i have tried to download your .exe, but when i tried to run it i got this error:

Traceback (most recent call last):
  File "pocra.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "autodex.py", line 22, in <module>
  File "webdriver_manager\chrome.py", line 40, in install
  File "webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
  File "webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
AttributeError: 'NoneType' object has no attribute 'split'

I just unzipped the .zip, and executed the .exe.

Have a nice day :)

**Comment by ruan-xian** [comment]
Hello! It seems like this is a somewhat recent issue with the webdriver manager; discussion here:
https://github.com/SergeyPirogov/webdriver_manager/issues/649
Have you done anything out of the ordinary with your Chrome install? Otherwise, I'm not sure what the root cause of this issue is - sorry to hear you weren't able to get it to work :(
